[build]
target = "x86_64-unknown-none"
target-dir = "build/kernel"
rustflags = [
    "-Ccode-model=kernel",
    "-Cpanic=abort",
    "-Coverflow-checks=false",
    "-Cno-redzone",
    "-Cllvm-args=-asm-macro-max-nesting-depth=256"
]

[profile.release]
lto = true
opt-level = 3
codegen-units = 1
strip = "symbols"
